version: "3.6"
services:
  app:
    build: .
    depends_on:
      - pg
    volumes:
      - .:/usr/src/app
    ports:
      - "31337:31337"
      - "8080:8080"
  pg:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg:
